apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service
  labels:
    app.kubernetes.io/name: backend-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: gitops-demo
automountServiceAccountToken: false

