apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Repository credentials (use secrets in production)
  repositories: |
    - url: https://github.com/anasadan/gitops.git
      name: gitops-repo

  # Resource tracking method
  application.resourceTrackingMethod: annotation

  # Health checks for custom resources
  resource.customizations.health.argoproj.io_Application: |
    hs = {}
    hs.status = "Progressing"
    hs.message = ""
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end
    return hs

  # Kustomize build options
  kustomize.buildOptions: --enable-helm

  # Status badge enabled
  statusbadge.enabled: "true"

  # Admin enabled (disable in production)
  admin.enabled: "true"

  # Dex configuration (for SSO - optional)
  # dex.config: |
  #   connectors:
  #     - type: github
  #       id: github
  #       name: GitHub
  #       config:
  #         clientID: $dex.github.clientID
  #         clientSecret: $dex.github.clientSecret
  #         orgs:
  #           - name: your-org

