apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Default policy for authenticated users
  policy.default: role:readonly

  # RBAC policies
  policy.csv: |
    # Roles
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, logs, *, *, allow
    p, role:admin, exec, *, */*, allow

    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, */dev-*, allow
    p, role:developer, logs, get, */*, allow
    p, role:developer, repositories, get, *, allow
    p, role:developer, projects, get, *, allow

    p, role:devops, applications, *, */*, allow
    p, role:devops, clusters, get, *, allow
    p, role:devops, repositories, *, *, allow
    p, role:devops, projects, *, *, allow
    p, role:devops, logs, get, */*, allow
    p, role:devops, exec, create, */*, allow

    # Group bindings
    g, admin, role:admin
    g, devops-team, role:devops
    g, developers, role:developer

  # Scopes for OIDC groups
  scopes: '[groups]'

