apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: app-of-apps
    app.kubernetes.io/part-of: gitops-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/anasadan/gitops.git
    targetRevision: HEAD
    path: argocd/applications
    directory:
      recurse: false
      include: '{dev.yaml,staging.yaml,production.yaml}'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

